# Generated by Django 5.2.17 on 2026-10-03 07:32

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100 level'), (200, '200 level'), (300, '300 level'), (400, '400 level'), (500, '500 level')], default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=6),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_units',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z]+/[A-Z]+/\\d{3}$', 'Use the format LEC/CSC/001.')])),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Engr', 'Engr')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,19}$', 'Enter a valid phone number, digits only, with an optional leading +.')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='students.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='students.lecturer'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'level'], name='students_co_departm_9c9ef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('staff_number'), name='uniq_lecturer_staff_ci'),
        ),
    ]
